apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocdproj-github
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/manikandanramdevops/argo.git
    targetRevision: HEAD
    path: application
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-application-github
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
